//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonasClient.PersonaWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://andreshw.servicios.persona.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int EdadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Servicio personas v1.0Soap", Namespace="http://andreshw.servicios.persona.org/", ConfigurationName="PersonaWebService.Serviciopersonasv10Soap")]
    public interface Serviciopersonasv10Soap {
        
        // CODEGEN: Generating message contract since element name ConsultarPersonasResult from namespace http://andreshw.servicios.persona.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://andreshw.servicios.persona.org/ConsultarPersonas", ReplyAction="*")]
        PersonasClient.PersonaWebService.ConsultarPersonasResponse ConsultarPersonas(PersonasClient.PersonaWebService.ConsultarPersonasRequest request);
        
        // CODEGEN: Generating message contract since element name ConsultarPersonaPorIdResult from namespace http://andreshw.servicios.persona.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://andreshw.servicios.persona.org/ConsultarPersonaPorId", ReplyAction="*")]
        PersonasClient.PersonaWebService.ConsultarPersonaPorIdResponse ConsultarPersonaPorId(PersonasClient.PersonaWebService.ConsultarPersonaPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPersonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPersonas", Namespace="http://andreshw.servicios.persona.org/", Order=0)]
        public PersonasClient.PersonaWebService.ConsultarPersonasRequestBody Body;
        
        public ConsultarPersonasRequest() {
        }
        
        public ConsultarPersonasRequest(PersonasClient.PersonaWebService.ConsultarPersonasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarPersonasRequestBody {
        
        public ConsultarPersonasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPersonasResponse", Namespace="http://andreshw.servicios.persona.org/", Order=0)]
        public PersonasClient.PersonaWebService.ConsultarPersonasResponseBody Body;
        
        public ConsultarPersonasResponse() {
        }
        
        public ConsultarPersonasResponse(PersonasClient.PersonaWebService.ConsultarPersonasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://andreshw.servicios.persona.org/")]
    public partial class ConsultarPersonasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PersonasClient.PersonaWebService.Persona[] ConsultarPersonasResult;
        
        public ConsultarPersonasResponseBody() {
        }
        
        public ConsultarPersonasResponseBody(PersonasClient.PersonaWebService.Persona[] ConsultarPersonasResult) {
            this.ConsultarPersonasResult = ConsultarPersonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPersonaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPersonaPorId", Namespace="http://andreshw.servicios.persona.org/", Order=0)]
        public PersonasClient.PersonaWebService.ConsultarPersonaPorIdRequestBody Body;
        
        public ConsultarPersonaPorIdRequest() {
        }
        
        public ConsultarPersonaPorIdRequest(PersonasClient.PersonaWebService.ConsultarPersonaPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://andreshw.servicios.persona.org/")]
    public partial class ConsultarPersonaPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ConsultarPersonaPorIdRequestBody() {
        }
        
        public ConsultarPersonaPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPersonaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPersonaPorIdResponse", Namespace="http://andreshw.servicios.persona.org/", Order=0)]
        public PersonasClient.PersonaWebService.ConsultarPersonaPorIdResponseBody Body;
        
        public ConsultarPersonaPorIdResponse() {
        }
        
        public ConsultarPersonaPorIdResponse(PersonasClient.PersonaWebService.ConsultarPersonaPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://andreshw.servicios.persona.org/")]
    public partial class ConsultarPersonaPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PersonasClient.PersonaWebService.Persona ConsultarPersonaPorIdResult;
        
        public ConsultarPersonaPorIdResponseBody() {
        }
        
        public ConsultarPersonaPorIdResponseBody(PersonasClient.PersonaWebService.Persona ConsultarPersonaPorIdResult) {
            this.ConsultarPersonaPorIdResult = ConsultarPersonaPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Serviciopersonasv10SoapChannel : PersonasClient.PersonaWebService.Serviciopersonasv10Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Serviciopersonasv10SoapClient : System.ServiceModel.ClientBase<PersonasClient.PersonaWebService.Serviciopersonasv10Soap>, PersonasClient.PersonaWebService.Serviciopersonasv10Soap {
        
        public Serviciopersonasv10SoapClient() {
        }
        
        public Serviciopersonasv10SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Serviciopersonasv10SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Serviciopersonasv10SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Serviciopersonasv10SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonasClient.PersonaWebService.ConsultarPersonasResponse PersonasClient.PersonaWebService.Serviciopersonasv10Soap.ConsultarPersonas(PersonasClient.PersonaWebService.ConsultarPersonasRequest request) {
            return base.Channel.ConsultarPersonas(request);
        }
        
        public PersonasClient.PersonaWebService.Persona[] ConsultarPersonas() {
            PersonasClient.PersonaWebService.ConsultarPersonasRequest inValue = new PersonasClient.PersonaWebService.ConsultarPersonasRequest();
            inValue.Body = new PersonasClient.PersonaWebService.ConsultarPersonasRequestBody();
            PersonasClient.PersonaWebService.ConsultarPersonasResponse retVal = ((PersonasClient.PersonaWebService.Serviciopersonasv10Soap)(this)).ConsultarPersonas(inValue);
            return retVal.Body.ConsultarPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonasClient.PersonaWebService.ConsultarPersonaPorIdResponse PersonasClient.PersonaWebService.Serviciopersonasv10Soap.ConsultarPersonaPorId(PersonasClient.PersonaWebService.ConsultarPersonaPorIdRequest request) {
            return base.Channel.ConsultarPersonaPorId(request);
        }
        
        public PersonasClient.PersonaWebService.Persona ConsultarPersonaPorId(int id) {
            PersonasClient.PersonaWebService.ConsultarPersonaPorIdRequest inValue = new PersonasClient.PersonaWebService.ConsultarPersonaPorIdRequest();
            inValue.Body = new PersonasClient.PersonaWebService.ConsultarPersonaPorIdRequestBody();
            inValue.Body.id = id;
            PersonasClient.PersonaWebService.ConsultarPersonaPorIdResponse retVal = ((PersonasClient.PersonaWebService.Serviciopersonasv10Soap)(this)).ConsultarPersonaPorId(inValue);
            return retVal.Body.ConsultarPersonaPorIdResult;
        }
    }
}
